---
- name: mount WebDAV share
  hosts:
    - localhost
  gather_facts: false
  become: yes

  tasks:

    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 300

    - name: Mount WebDAV download share
      mount:
        name: /mnt/webdav
        src: "https://download.acc.dh.unimaas.nl"
        fstype: davfs
        state: mounted
        opts: "username="{{ Username }}",password="{{ Token }}""
