---
- name: Install GNOME desktop and mount WebDAV share
  hosts:
    - localhost
  gather_facts: false
  become: yes

  tasks:

    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 300

    - name: Install GNOME desktop
      apt:
        name:
          - ubuntu-desktop
          - gnome-shell
          - gnome-session
        state: present

    - name: Mount WebDAV download share
      mount:
        name: /mnt/webdav
        src: "https://download.acc.dh.unimaas.nl"
        fstype: davfs
        state: mounted
        opts: "username={{ webdav_username }},password={{ webdav_token }}"
      vars_prompt:
        - name: "webdav_username"
          prompt: "Enter WebDAV username"
          private: yes
        - name: "webdav_token"
          prompt: "Enter WebDAV password"
          private: yes

    - name: Mount WebDAV upload share
      mount:
        name: /mnt/webdav
        src: "https://upload.acc.dh.unimaas.nl"
        fstype: davfs
        state: mounted
        opts: "username={{ webdav_username }},password={{ webdav_token }}"
      vars_prompt:
        - name: "webdav_username"
          prompt: "Enter WebDAV username"
          private: yes
        - name: "webdav_token"
          prompt: "Enter WebDAV password"
          private: yes