---
- name: Download cyberduck package
  win_get_url:
    url: https://update.cyberduck.io/windows/Cyberduck-Installer-8.5.6.39394.exe
    dest: C:\temp\cyberduck.exe

- name: Ensure cyberduck is installed through win_package
  become: yes
  win_package:
    path: C:\temp\cyberduck.exe
    state: present